#ifndef _ALTERA_C5_H_
#define _ALTERA_C5_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'hps' in
 * file 'hps.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'DataMover_0', class 'DataMover'
 * The macros are prefixed with 'DATAMOVER_0_'.
 * The prefix is the slave descriptor.
 */
#define DATAMOVER_0_COMPONENT_TYPE DataMover
#define DATAMOVER_0_COMPONENT_NAME DataMover_0
#define DATAMOVER_0_BASE 0x0
#define DATAMOVER_0_SPAN 8192
#define DATAMOVER_0_END 0x1fff

/*
 * Macros for device 'generic_sys_id', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'GENERIC_SYS_ID_'.
 * The prefix is the slave descriptor.
 */
#define GENERIC_SYS_ID_COMPONENT_TYPE altera_avalon_sysid_qsys
#define GENERIC_SYS_ID_COMPONENT_NAME generic_sys_id
#define GENERIC_SYS_ID_BASE 0x2000
#define GENERIC_SYS_ID_SPAN 8
#define GENERIC_SYS_ID_END 0x2007
#define GENERIC_SYS_ID_ID 305441741
#define GENERIC_SYS_ID_TIMESTAMP 1710365883

/*
 * Macros for device 'master_pio_led_blue', class 'altera_avalon_pio'
 * The macros are prefixed with 'MASTER_PIO_LED_BLUE_'.
 * The prefix is the slave descriptor.
 */
#define MASTER_PIO_LED_BLUE_COMPONENT_TYPE altera_avalon_pio
#define MASTER_PIO_LED_BLUE_COMPONENT_NAME master_pio_led_blue
#define MASTER_PIO_LED_BLUE_BASE 0x2010
#define MASTER_PIO_LED_BLUE_SPAN 16
#define MASTER_PIO_LED_BLUE_END 0x201f
#define MASTER_PIO_LED_BLUE_BIT_CLEARING_EDGE_REGISTER 0
#define MASTER_PIO_LED_BLUE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MASTER_PIO_LED_BLUE_CAPTURE 0
#define MASTER_PIO_LED_BLUE_DATA_WIDTH 1
#define MASTER_PIO_LED_BLUE_DO_TEST_BENCH_WIRING 0
#define MASTER_PIO_LED_BLUE_DRIVEN_SIM_VALUE 0
#define MASTER_PIO_LED_BLUE_EDGE_TYPE NONE
#define MASTER_PIO_LED_BLUE_FREQ 100000000
#define MASTER_PIO_LED_BLUE_HAS_IN 0
#define MASTER_PIO_LED_BLUE_HAS_OUT 1
#define MASTER_PIO_LED_BLUE_HAS_TRI 0
#define MASTER_PIO_LED_BLUE_IRQ_TYPE NONE
#define MASTER_PIO_LED_BLUE_RESET_VALUE 0

/*
 * Macros for device 'Decoder_0', class 'Codec'
 * The macros are prefixed with 'DECODER_0_'.
 * The prefix is the slave descriptor.
 */
#define DECODER_0_COMPONENT_TYPE Codec
#define DECODER_0_COMPONENT_NAME Decoder_0
#define DECODER_0_BASE 0x4000
#define DECODER_0_SPAN 8192
#define DECODER_0_END 0x5fff

/*
 * Macros for device 'Encoder_0', class 'Codec'
 * The macros are prefixed with 'ENCODER_0_'.
 * The prefix is the slave descriptor.
 */
#define ENCODER_0_COMPONENT_TYPE Codec
#define ENCODER_0_COMPONENT_NAME Encoder_0
#define ENCODER_0_BASE 0x6000
#define ENCODER_0_SPAN 8192
#define ENCODER_0_END 0x7fff


#endif /* _ALTERA_C5_H_ */
