#!/bin/sh
#
# Fetch date from host
#

case "$1" in
  start)
    echo "Fetching date from host..."
    ntpdate 192.168.1.1
    ;;
  stop)
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?